apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    # These annotations configure HOW the ALB behaves
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  # This is the crucial line that was missing from your live configuration.
  # It explicitly tells the 'alb' controller to manage this Ingress.
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 5000
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 5001
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 5002
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-gateway-service
            port:
              number: 80